version: '3'
services:
  sqldb:
    container_name: sqldb
    build: 
      context: ./
      dockerfile: ./Dockerfile
    working_dir: /
    ports:
      - 5432:5432
    networks:
      vpcbr:
        ipv4_address: 10.5.0.5
    restart: always

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16